### ISSUE TITLE
save-interval- checkpoints

### ISSUE THREAD

**Issue by Wadha-Almattar** [YijinHuang/SSiT#10]
Hi,
On of the parameters at the model training is **save-interval** where its default value is 20. So, during the training a checkpoint will be saved after each 20 epochs.  In the downstream task with fine-tuning, which checkpoint should I utilized in this case. Now, I fine-tune with the last checkpoint which has 300 number. Does it make difference in SSL if using the last one to fine-tune or should I try them all.

**Comment by YijinHuang** [comment]
All experiments in the paper were trained using the last checkpoint. While I didn’t test other checkpoints, previous works typically utilize the final checkpoint for downstream tasks.
