### ISSUE TITLE
关于论文中其他自监督模型的对比实验

### ISSUE THREAD

**Issue by Eutopia01** [YijinHuang/SSiT#11]
作者您好!在文章中，TABLE I列出了多种自监督模型的对比实验；我用EyePACS的训练集对Moco-v3进行预训练，使用backbone也为VIT-S，最后在APTOS2019数据集上finetune得到最终的Kappa值为87%左右，而在您的论文中可以达到90%左右的结果，想问一下除了数据量不一样以外，还有哪些需要注意的地方吗？您对Moco-v3进行训练时，是完全遵循原始论文中的设置还是对哪些超参数进行修改呢？还有一个问题，您在进行预训练的时候input-size设置为224×224，而评估的时候设置为384×384，请问这个的不同有什么作用吗？期待您的指导，十分感谢。

**Comment by YijinHuang** [comment]
您好，

1. 因为APTOS2019数据集只公开了训练集，因此在实验中我是将该训练集进一步随机划分成训练集/测试集/验证集，所以我认为该性能差距可能是数据集划分不同导致的，此外训练的超参您可以参考我的设置。
2. 在fine-tuning中使用相较于pre-training更高的分辨率会提升性能，同时减少pre-training阶段的计算成本，这是在ViT论文原文中提到的一个点（附录B.1.1）。

如果还有其他问题，欢迎提问。
