### ISSUE TITLE
Are four V100 (16 GB memory per GPU) adequate to run the code from scratch using DDP? 

### ISSUE THREAD

**Issue by osivaz61** [YijinHuang/SSiT#12]

**Comment by YijinHuang** [comment]
Thank you for your question. In our training setting, 64GB GPU is sufficient to train SSiT.

**Comment by osivaz61** [comment]
You said that 64GB is sufficient. However, there is a difference between 4 V100(16GB per GPU) and only one GPU that has 64GB GPU memory.
