### ISSUE TITLE
compare the result with a plain backbone.

### ISSUE THREAD

**Issue by osivaz61** [YijinHuang/SSiT#13]
I am a newbie. I am trying to understand the process. Did you compare the results of the plain backbone (supervised model like in Lesion-Based Contrastive Learning) with the proposed model? Are the results of the plain model or the proposed model high? There is no comparison.

**Comment by YijinHuang** [comment]
Thank you for your question. Random init. is the supervised plain model, which is a plain model that randomly initialized trained on downstream datasets.
