### ISSUE TITLE
Checkpoints for SOTA SSL models 

### ISSUE THREAD

**Issue by Wadha-Almattar** [YijinHuang/SSiT#15]
I'm wondering if you could share the checkpoints for the SOTA SSL models mentioned in your table results?. Also, Did you run  SOTA SSL models from their original implementation page? if could mention your source, it will be appreciated. 

Thanks in advance,

**Comment by YijinHuang** [comment]
The results from all compared methods are obtained using their original implementations, with the exception of the reconstruction method. Unfortunately, I did not retain all the checkpoints for the other methods. However, if you run their original implementations with the same data augmentation settings as SSiT, which are optimized for fundus image pre-training, you should achieve comparable checkpoints.
